# Generated by Django 3.0.7 on 2024-09-08 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0009_auto_20240908_1954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='year',
        ),
    ]
