# Generated by Django 3.0.7 on 2024-09-09 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0022_auto_20240909_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='passengers',
            field=models.IntegerField(default=1),
        ),
    ]
